### ISSUE TITLE
Clear Dues Page: Issues

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#189]
**Issues:**

- [ ] The value amounted to " Current dues payable from 1 dec " is incorrect

 - [x] We can see the current payroll cycle, in previous payroll header. If we have only one month in cycle - which is the current month let us show the text " No previous month to display " ( follow design already done when no staff is present and you search a record. @ShubhamModi004 speak to me if you have confusions.

- [x] Question: Why do we have 30 days in December?

- [x] In November, why do we have 30/29 in days worked? that's incorrect

![image](https://user-images.githubusercontent.com/55691499/101159734-da71ab00-3653-11eb-91e1-48320828aff7.png)

**Comment by sharangsamonkar** [comment]
Fixed the last 3. Have ticked them off. 

The first one - did not understand. Do you mean the value is incorrect? Or is the sign showing up incorrect?

Have checked the value for a few staff members. They seem correct. If you find someone incorrect, please raise a separate ticket.

For the sign, we need think of how we will show the positive and negative numbers since the ui is grey.

**Comment by HazelColaco19** [comment]
Need to confirm on the First point. rest 3 fixed

**Comment by HazelColaco19** [comment]
Creating another issue. closing this
