### ISSUE TITLE
Back button on edit staff shows the salary type (monthly,hourly,etc.) screen

### ISSUE THREAD

**Issue by sharangsamonkar** [ajency/Dhanda-App#192]
1. Click on edit salary info (second edit button)
2. Press back button or back on the top left corner/
3. Shows the salary type screen.

Expected behaviour: Should come on the edit staff page.

**Comment by ShubhamModi004** [comment]
Buttons are disabled on salary type screen you cannot edit them.

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Even if the salary type cannot be edited, we cannot re-direct the user to this screen since it's not in edit flow at least in this release.

**Comment by HazelColaco19** [comment]
fixed

**Comment by HazelColaco19** [comment]
This can be now seen for all staff types. reopening the ticket. @ShubhamModi004

**Comment by HazelColaco19** [comment]
Not fixed @ShubhamModi004

**Comment by sharangsamonkar** [comment]
You need to go two steps in front and then go back.

**Comment by sharangsamonkar** [comment]
click edit > continue and the do back.

**Comment by HazelColaco19** [comment]
fixed

**Comment by ShubhamModi004** [comment]
Edit staff implementation was done in sprint 1, where I had to display all the screens, screen redirection was necessary because code was already implemented to go in steps. Implemented a subtle change without breaking any UI and logic implemented, also if in any case we reach the screen where fields shouldn't be edit, made the content uneditable.

Later to completely hide the screen implemented a logic to never reach the screen anyhow from the first screen, my logic worked for first edit screen but didn't work for the second edit screen, implemented the same for second screen later.
