### ISSUE TITLE
Transaction Types should not be viewed with an underscore. It should be init capitalised. Currently it says " payment_taken "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#205]
![image](https://user-images.githubusercontent.com/55691499/101181605-17996580-3673-11eb-86da-11c19b6161d0.png)

**Comment by HazelColaco19** [comment]
Can still see all of the types with an underscore @ShubhamModi004 @sharangsamonkar It should been " Payment Taken " and so on.

**Comment by ShubhamModi004** [comment]
Cannot replicate the same.
Assigning it to QA thinking it got resolved while resolving the other issues.
Issue raised similar to issue raised on issue number #207

**Comment by HazelColaco19** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Can still see this for the following

1. loan_given @sharangsamonkar @ShubhamModi004

**Comment by HazelColaco19** [comment]
fixed

**Comment by ShubhamModi004** [comment]
After finishing the sprint, the payment_taken and payment_given I didn't add to my translate files, later after adding it resolved the issue for me and from my end I was testing it on add transaction. Later on the call with @sharangsamonkar and @HazelColaco19, while resolving some other issue I realised the issue was on edit transaction and not add transaction.
