### ISSUE TITLE
Hours and minutes in counter must be center aligned 

### ISSUE THREAD

**Issue by SumeshAj** [ajency/Dhanda-App#24]
Hours and minutes in counter must be center aligned in Late Fine, add overtime.
![2020-10-29](https://user-images.githubusercontent.com/72379338/97559069-f8b80b80-1a02-11eb-938d-3254b2b25e83.jpg)

**Comment by SumeshAj** [comment]
![2020-11-04](https://user-images.githubusercontent.com/72379338/98111118-22bb7300-1ec6-11eb-8207-e7f7669ad338.jpg)

**Comment by sharangsamonkar** [comment]
Issue seen only on Oppo F3

**Comment by ShubhamModi004** [comment]
Cannot replicate the same on 3 emulators and the device I have

**Comment by sharangsamonkar** [comment]
@HazelColaco19 : Top and bottom space is not proper on OnePlus and Realme XT.

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Can you please check this out as well

**Comment by ShubhamModi004** [comment]
The library I am using has limited design options, can we implement a design change making the arrows clickable and on click of arrows changes the number

**Comment by sharangsamonkar** [comment]
As discussed, 
1. Remove wheel picker and make the top and down button clickable
2. Allow the user to type the value - validation: if hours is more than 23 default to 23 and if minutes is more than 59 default to 59.

**Comment by HazelColaco19** [comment]
@ShubhamModi004 
1. Disable the click on arrows since it is inconsistent. It works only once if you click the top arrow for minutes
2. If the user enters hours/ minutes values more than 23 hours or 59 minutes then the picker glitches.

**Comment by ShubhamModi004** [comment]
@HazelColaco19 

### Point 1) 
I have an approach increasing the width of  the touchable area for the arrow button , makes it easier to click the arrow button
bottom arrow button is clickable at present, but since area is too small it feels like you are clicking on it but the click doesn't get triggered. **(Already implemented)**

### Point 2)
If we enter the time, if the user enters numbers above 23 then as discussed I am defaulting to 23. **(Already Implemented)**
Approach I can suggest is throw a Toast message error saying enter valid time instead of defaulting. **(Not Implemented yet)**

**Comment by HazelColaco19** [comment]
Let's discuss the approach on the call. However, the same fix should be applied too late fine modal. @ShubhamModi004

**Comment by HazelColaco19** [comment]
The counter has now been changed for both ( Hours/ Minutes ). The above counters don't exist anymore. We can close this ticket.
