### ISSUE TITLE
 Work basis salary is not calculated ( shows blank value on transaction screen )

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Dhanda-App#321]
Related Issue: #320 

Staff Name: Work Basis Hazel

Expected: Check the salary in the transaction detail screen

![image](https://user-images.githubusercontent.com/55691499/104737486-4cb4cf80-576a-11eb-8f85-d91fcbd8faa7.png)

**Comment by ShubhamModi004** [comment]
Response from the api that I get is **"salary": null**  for a work_basis, now since employee is a work_basis there might not be a salary for the employee.


{"amountDue": 900.9, "daysTotal": 31, "daysWorked": 2, "hoursWorked": "00:00", "periodEnd": "2021-02-13", "periodStart": "2021-01-14", "periodType": "monthly", "salary": null, "salaryType": "work_basis"}

**Comment by HazelColaco19** [comment]
@ShubhamModi004 Can we add " Not Applicable " when Sharang is passing 0 to you for the salary value of work basis staff?

**Comment by snehaajency** [comment]
fixed
![Screenshot_2021-02-04-17-58-06-530_com app ogaji test](https://user-images.githubusercontent.com/4660706/106892823-a4fc4300-6712-11eb-89ac-6ed15a045572.jpg)
